### ISSUE TITLE
Data set request

### ISSUE THREAD

**Issue by LRuiRui517** [ming053l/CSAKD#2]
Great work, can the data set be shared? Or please share it with me at maizai413@163.com.Thank you very much

**Comment by pinpolhoxx** [comment]
try this

https://bit.ly/3TCbXO6
Pass: changeme

you may need to install the c compiler

**Comment by ming053l** [comment]
Hi, I hava released the dataset at the repository, please feel free to download it.

**Comment by LRuiRui517** [comment]
> Hi, I hava released the dataset at the repository, please feel free to download it.

Thank you very much for sharing your valuable dataset. I have repeatedly downloaded many times, each time the decompression failed, changed several decompression tools, I want to know whether the file is the problem.
Again, thank you for your generous sharing, and I look forward to your reply.

Best regards.

**Comment by ming053l** [comment]
Hello Maizai,

Sorry for lately reply, because the file is huge (this includes
Ground-truth, LR-HSI, HRLSI pairs), we use 7z to save the file. In order to
upload it to the cloud, we split the file.

You can refer to the specific opening method, which may vary according to
your computer settings or operating system.

https://bbs.kafan.cn/thread-2247548-1-1.html

https://www.reddit.com/r/synology/comments/k6228n/auto_unzip_7z001files/

If it still doesn't work, I'll try to upload it to another place for you to
access, but it may take some time.

Best Regards,

Chia-Ming Lee

**Comment by ming053l** [comment]
@LRuiRui517 

Hi, do you successfully download it? I would like to know people can sucessfully download it or not. Thanks!
